.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. micro_qt test_micro_qt
clean: FORCE
	$(MAKE) -C .. micro_qt_clean test_micro_qt_clean
check: FORCE
	$(MAKE) -C .. test_micro_qt_check
micro-qt micro-qt.exe: FORCE
	 $(MAKE) -C .. micro_qt
apk: FORCE
	$(MAKE) -C .. micro_qt_apk
